//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Game
{
    using System;
    using System.Collections.Generic;
    
    public partial class Army
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int Attack { get; set; }
        public int Defence { get; set; }
        public int MagicResist { get; set; }
        public int Knowledge { get; set; }
        public int Quantity { get; set; }
        public Nullable<int> KingdomId { get; set; }
    
        public virtual Kingdom Kingdom { get; set; }
    }
}
